Реализован логер используя паттерн Strategy
GulnazIV/dp-2024-lab02 pull request #2
Opened 2024-10-24 19:21 UTC by GulnazIV

2024-10-24 21:43 UTC, Rognak commented on main.py
> +class IStrategyLogger(ABC):
Интерфейсы необходимо вынести в отдельный модуль, как и реализации стратегий

2024-10-24 21:45 UTC, Rognak commented on main.py
> +    def _create_file(self, path_directory: str) -> None:
Название метода не отражает того, что оно делает. По факту здесь создается лишь путь до файла

2024-10-24 21:46 UTC, Rognak commented on main.py
> +    def _create_file(self, path_directory: str) -> None:
Для работы с файловой системой лучше использовать Pathlib

2024-10-24 21:53 UTC, Rognak commented on main.py
> +        (ссылается в родительский класс FileLogStrategy с измененным сообщением)
Слишком сильно описывать не нужно. Достаточно сообщения о том, что делает метод

2024-10-24 21:54 UTC, Rognak commented on main.py
> +        self._strategy = strategy
Нет управления стратегией в runtime

2024-10-24 22:12 UTC, Rognak commented on test.py
> +    def test_logging_file(self):
При тестировании необходимо избегать настоящей записи в файл. 
https://stackoverflow.com/questions/33650568/mock-open-function-used-in-a-class-method

2024-10-24 22:12 UTC, Rognak commented on test.py
> +    def test_logging_uppercase_file(self):
Аналогично

2024-10-24 22:14 UTC, Rognak commented on main.py
> +    _strategy: IStrategyLogger
Зачем?

2024-10-24 22:18 UTC, Rognak commented on module/log_levels.py
> +class LEVELS(Enum):
Название класса не должно быть капсом

2024-10-24 22:18 UTC, Rognak commented on test.py
> +from main import Logger,FileLogStrategy, UpperCaseFileLogStrategy, ConsoleLogStrategy
Пробел

2024-10-24 22:27 UTC, Rognak commented on .github/workflows/CI.yml
> +    branches: [ "feature" ]
Для чего этот фильтр?

2024-10-24 22:30 UTC, Rognak requested changes
Не все коммиты соответствуют Conventional Commits. Исключением из правила может быть MergeCommit

2024-10-25 06:13 UTC, vladushka2000 commented on main.py
> +class IStrategyLogger(ABC):
Мне не нравится название класса. Мы не называем сущности как паттерны, даем осмысленные названия

2024-10-25 06:13 UTC, vladushka2000 commented on main.py
> +    Интерфейс паттерна Стратегия
Это интерфейс логгера, не стратегии

2024-10-25 06:14 UTC, vladushka2000 commented on main.py
> +class ConsoleLogStrategy(IStrategyLogger):
Беда с названиями классов. Поправить

2024-10-25 06:17 UTC, vladushka2000 commented on main.py
> +        self._strategy = strategy
Добавить публичный сеттер для задания стратегии в рантайм

2024-10-25 06:25 UTC, vladushka2000 commented
Как бы хотелось: должен быть реализован интерфейс для логгера, который принимает в рантайме объекты врайтеров.  Врайтеры также имеют свой интерфейс. Чтобы не брать врайтеры "из воздуха", реализовать фабричный метод для каждого типа врайтера - запись в консоль, в файл, в файл капсом.
Я хз что у твоей группы по времени на 2 лабу, но она очень простой получается, если реализовывать чисто стратегию

2024-10-25 07:53 UTC, vladushka2000 commented on main.py
> +class Logger:
нету интерфейса Логгера

2024-10-29 05:51 UTC, vladushka2000 commented on components/logger.py
> +            formatted_message = f"{time_stamp} [{level}] {message}"
давай форматирование сообщения в отдельный приватный метод вынесем. Это не ответственность метода для логирования

2024-10-29 05:52 UTC, vladushka2000 commented on const/log_levels.py
> +class Levels(Enum):
нет док стринги, + написать комментарии к каждому уровню лога

2024-10-29 05:56 UTC, vladushka2000 commented on components/log_strategy.py
> +    def _create_path_file(self, path_directory: str) -> None:
по-хорошему, для работы с файлами должен быть отдельный класс - FileHandler. Ответственность Врайтера - запись куда-либо. Я уж не буду заставлять его делать, сроки по сдачи лабы уже наступили практически

2024-10-29 06:07 UTC, Rognak commented on .github/workflows/CI.yml
> +    branches: [ "feature" ]
Не нужен данный фильтр) Работа же может продолжиться не только в ветке feature

2024-10-29 06:08 UTC, Rognak commented on components/logger.py
> +    def set_log_strategy(self, log_strategy: IWriter):
set_writer

2024-10-29 06:09 UTC, Rognak approved these changes
Поправить небольшие замечания и можно заливать

2024-10-29 07:47 UTC, vladushka2000 commented
все кайф, заливай

2024-10-29 07:48 UTC, vladushka2000 approved these changes

2024-10-31 05:37 UTC, Rognak approved these changes

2024-11-01 08:57 UTC, merged